repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
      - id: terraform_docs
        description: Generate documentation for Terraform modules
        args:
          - --args=--config=.terraform-docs.yml
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_tflint     
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
